version: '3'
services:
  graphite-statsd:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - ./load/statsd.conf:/opt/statsd