# ---------------------------
# Generated by rel-engage

# This task tells make how to 'build' n-gage. It npm installs n-gage, and # Once that's done it overwrites the file with its own contents - this
# ensures the timestamp on the file is recent, so make won't think the file
# is out of date and try to rebuild it every time
node_modules/@financial-times/rel-engage/index.mk:
	@echo "Updating rel-engage"
	@npm install --save-dev @financial-times/rel-engage
	@touch $@

# If, by the end of parsing your `Makefile`, `make` finds that any files
# referenced with `-include` don't exist or are out of date, it will run any
# tasks it finds that match the missing file. So if n-gage *is* installed
# it will just be included; if not, it will look for a task to run
-include node_modules/@financial-times/rel-engage/index.mk

# End generated by rel-engage
# ---------------------------

NEO4J_BOLT_URL=bolt://localhost:7687
NEO4J_VERSION=3.5.0

env:
	echo "No secret environment variables needed in test"

verify:

unprepublish:
	sed s/"dist\/"/"src\/"/ packages/tc-ui/package.json > tmp && mv tmp packages/tc-ui/package.json


# note that this invokes npm install, and in package.json there is a postinstall script
# defined too, which installs all the node_modules for the packages
install: unprepublish

prepublish:
	babel packages/tc-ui/src -D --out-dir packages/tc-ui/dist
	sed s/"src\/"/"dist\/"/ packages/tc-ui/package.json > tmp && mv tmp packages/tc-ui/package.json

monorepo-publish: prepublish
	npx athloi version --concurrency 10 $(CIRCLE_TAG)
	npx athloi publish --concurrency 10 -- --access public

.PHONY: test

.PHONY: cypress-open
cypress-open: ## cypress-open: Opens the Cypress.io Electron test runner. Expects a local application server to be running concurrently.
	TREECREEPER_TEST=true \
	cypress open

.PHONY: cypress-run
cypress-run:
	@if [ -z $(CI) ]; \
		then TREECREEPER_TEST=true cypress run; \
		else TREECREEPER_TEST=true cypress run -- --parallel; \
	fi

.PHONY: cypress-verify
cypress-verify:
	TREECREEPER_TEST=true \
	cypress verify

deploy-aws:
	aws cloudformation deploy --stack-name biz-ops-kinesis --template-body file://$(shell pwd)/aws/cloudformation/biz-ops-kinesis.yaml

test:
	@if [ -z $(CI) ]; \
		then TREECREEPER_TEST=true TREECREEPER_SCHEMA_DIRECTORY=example-schema DEBUG=true TIMEOUT=500000 \
			jest --config="./jest.config.js" "${pkg}.*__tests__.*${spec}.*.spec.js" --testEnvironment=node --watch; \
		else TREECREEPER_TEST=true TREECREEPER_SCHEMA_DIRECTORY=example-schema \
			jest --config="./jest.config.js" "__tests__.*/*.spec.js" --testEnvironment=node --maxWorkers=1 --ci --reporters=default --reporters=jest-junit --detectOpenHandles --forceExit; \
	fi

run-app: build-statics
	TREECREEPER_TEST=true TREECREEPER_SCHEMA_DIRECTORY=example-schema nodemon --inspect demo/api.js

build-statics:
	@if [ -z $(CI) ]; \
		then $(info Webpack bundling modules ...) ./node_modules/.bin/webpack --mode=development; \
		else $(info Webpack bundling modules ...) webpack --mode=production; \
	fi

run-db:
	docker-compose up

run:
	@concurrently "make run-db" "make run-app"

init-db:
	TREECREEPER_SCHEMA_DIRECTORY=example-schema packages/tc-api-db-manager/index.js

e2e-test:
	start-server-and-test "make run-app" http-get://localhost:8888/MainType/create "make cypress-run"

run-test-db:
	java -version; \
  mkdir -p neo4j; \
  wget -q dist.neo4j.org/neo4j-community-$(NEO4J_VERSION)-unix.tar.gz; \
  tar -xzf neo4j-community-$(NEO4J_VERSION)-unix.tar.gz -C neo4j --strip-components 1; \
  sed -i "s|#dbms.security.auth_enabled=false|dbms.security.auth_enabled=false|g" neo4j/conf/neo4j.conf;\
  ./scripts/neo4j-plugins; \
	dbms_memory_heap_initial_size="1024m" dbms_memory_heap_max_size="1024m" neo4j/bin/neo4j start; \
  ./scripts/neo4j-wait-for-start;
	make init-db

clean-deps: unprepublish
	rm -rf packages/*/node_modules
	rm -rf node_modules
	rm package-lock.json
	npm install
