version: 2

references:

  default_container_config: &default_container_config
    working_directory: ~/biz-ops-api
    docker:
      - image: circleci/node:8.11.1-browsers
    environment:
      NEO4J_VERSION: "3.2.9"

  workspace_root: &workspace_root
    ~/

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - v1-dependency-npm-{{ checksum "package.json" }}-
        - v1-dependency-npm-{{ checksum "package.json" }}
        - v1-dependency-npm-

  cache_node_modules: &cache_node_modules
    save_cache:
      key: v1-dependency-npm-{{ checksum "package.json" }}-{{ epoch }}
      paths:
        - ./node_modules/

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout

      - *restore_node_modules

      - run:
          name: Install dependencies
          command: |
            npm install --no-save
            npm update --no-save

      - *cache_node_modules

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - biz-ops-api

  test:
    <<: *default_container_config
    steps:
      - *attach_workspace

      - run:
          name: Prepare neo4j database
          command: |
            java -version
            mkdir -p neo4j
            wget -q dist.neo4j.org/neo4j-enterprise-$NEO4J_VERSION-unix.tar.gz
            tar -xzf neo4j-enterprise-$NEO4J_VERSION-unix.tar.gz -C neo4j --strip-components 1
            sed -i "s|#dbms.security.auth_enabled=false|dbms.security.auth_enabled=false|g" neo4j/conf/neo4j.conf
            ./scripts/neo4j-plugins
            dbms_memory_heap_initial_size="1024m" dbms_memory_heap_max_size="1024m" neo4j/bin/neo4j start
            ./scripts/neo4j-wait-for-start
            node server/init-db.js
      - run:
          name: Run tests
          command: npm test

      - store_artifacts:
          path: coverage
          destination: /coverage

  lint:
    <<: *default_container_config
    steps:
      - *attach_workspace

      - run:
          name: Lint
          command: npm run lint-ci

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install

experimental:
  notify:
    branches:
      only:
        - master
