name: Package
description: A library, component, toolkit or other group of code which can be used by systems.
rank: 25
properties:
  code:
    type: Code
    required: true
    unique: true
    canIdentify: true
    useInSummary: true
    pattern: PACKAGE_NAME
    label: Code
    description: |
      The unique identification for this package. The format is defined as `ecosystem:publishedPackageName`. For example npm:@financial-times/blah or composer:foo.
  name:
    type: Name
    canIdentify: true
    useInSummary: true
    label: Name
    description: The short name for the package which will be output on screens and reports.
  description:
    type: Paragraph
    canIdentify: true
    label: Description
    description: |
      A brief overview of what the package does and why, from the user's perspective.
      Note that multiple paragraphs and other markdown features are not supported in this field.
  repositories:
    type: Repository
    deprecationReason: Replaced by repository, which has a singular name befitting this one-to-one relationship
    direction: outgoing
    label: Source code repositories
    relationship: HAS_REPO
    description: The repositories which store this package's source code and/or configuration.
  repository:
    type: Repository
    direction: outgoing
    label: Source code repositories
    relationship: HAS_REPO
    description: The repository which stores this package's source code and/or configuration.
  maintainedBy:
    type: Team
    direction: outgoing
    label: Maintained by team
    relationship: MAINTAINED_BY
    description: The team which maintained the package.
  installedBy:
    type: System
    direction: incoming
    label: Installed by system
    relationship: INSTALLS
    description: System which installs this package.
    hasMany: true
