name: Product
description: |
  Anything sold by the FT for use by an external entity,
  or produced by an area of FT technology to be used by another internal area.
rank: 10
properties:
  code:
    type: Code
    required: true
    unique: true
    canIdentify: true
    isCore: true
    pattern: STRICT_CODE
    label: Code
    description: |
      Unique code for the product. Must be lowercase, and ideally only letters,
      numbers and hyphens.
    fieldset: general
  name:
    type: Name
    canIdentify: true
    isCore: true
    label: Name
    description: |
      The name generally used to refer to the product.
    fieldset: general
  description:
    type: Paragraph
    isCore: true
    label: Description
    description: |
      Brief description of what the product is and why it exists.
    fieldset: general
  serviceTier:
    type: ServiceTier
    canFilter: true
    isCore: true
    label: Service tier
    description: The service tier (level of support) given to this product.
    fieldset: general
  primaryURL:
    type: Url
    canIdentify: true
    isCore: true
    label: Primary URL
    description: The main url the product is served on.
    fieldset: general
  lifecycleStage:
    type: ProductLifecycle
    canFilter: true
    label: Lifecycle stage
    description: The product's current lifecycle stage.
    fieldset: general
  productOwners:
    type: Person
    direction: outgoing
    label: Product owners
    relationship: HAS_PRODUCT_OWNER
    description: The product's owner or owners.
    hasMany: true
    fieldset: network
  dependencies:
    type: System
    direction: outgoing
    label: Direct dependencies
    relationship: DEPENDS_ON
    description: The systems the product directly depends on.
    hasMany: true
    fieldset: network
  recursiveDependencies:
    type: System
    direction: outgoing
    label: Recursive dependencies
    relationship: DEPENDS_ON
    description: |
      The systems the product depends on, either directly or indirectly. This is
      populated by traversing the dependency tree of each direct dependency,
      and the list does not need to be manually maintained.
    hasMany: true
    isRecursive: true
    fieldset: network
  productDependencies:
    hasMany: true
    hidden: true
    type: Product
    relationship: DEPENDS_ON
    direction: outgoing
    description: Products that this product depends on.
    label: Product dependencies
    fieldset: network
  productDependents:
    hasMany: true
    hidden: true
    type: Product
    relationship: DEPENDS_ON
    direction: incoming
    description: Products that depend on this product.
    label: Product dependents
    fieldset: network
fieldsets:
  general:
    heading: General information
  network:
    heading: Network
