name: Product
description: Anything sold by the FT for use by an external entity, OR produced by an area of FT technology to be used by another internal area.
properties:
  code:
    type: Word
    required: true
    unique: true
    canIdentify: true
    pattern: STRICT_CODE
    label: Code
    description: 'Unique code/id for this item'
  description:
    type: Paragraph
    label: Description
    description: Brief description of what the product does
  name:
    type: Word
    canIdentify: true
    label: Name
    description: The name generally used to refer to the product
  serviceTier:
    type: ServiceTier
    # required: true
    canFilter: true
    label: Service tier
    description: The product's service tier level
  primaryURL:
    type: Url
    canIdentify: true
    label: Primary URL
    description: The main url the product is served on
  lifecycleStage:
    type: ProductLifecycle
    canFilter: true
    label: Lifecycle stage
    description: Lifecycle stage of the product
  productOwners:
    type: Person
    direction: outgoing
    label: Product owners
    relationship: HAS_PRODUCT_OWNER
    description: The product's owner
    hasMany: true
  dependencies:
    type: System
    direction: outgoing
    label: Direct dependencies
    relationship: DEPENDS_ON
    description: The systems the product directly depends on
    hasMany: true
  recursiveDependencies:
    type: System
    direction: outgoing
    label: Recursive dependencies
    relationship: DEPENDS_ON
    description: 'The systems the product depends on, either directly or indirectly'
    hasMany: true
    isRecursive: true
  productDependencies:
    hasMany: true
    hidden: true
    type: Product
    relationship: DEPENDS_ON
    direction: outgoing
    description: Products that this product depends on
    label: Product dependencies
  productDependents:
    hasMany: true
    hidden: true
    type: Product
    relationship: DEPENDS_ON
    direction: incoming
    description: Products that depend on this product
    label: Product dependents
