name: Product
description: Anything sold by the FT for use by an external entity, OR produced by an area of FT technology to be used by another internal area.
properties:
  code:
    type: Word
    required: true
    unique: true
    canIdentify: true
    pattern: STRICT_CODE
    label: Code
    description: 'Unique code/id for this item'
  description:
    type: Paragraph
    label: Description
    description: Brief description of what the product does
  name:
    type: Word
    canIdentify: true
    label: Name
    description: The name generally used to refer to the product
  serviceTier:
    type: ServiceTier
    # required: true
    canFilter: true
    label: Service tier
    description: The product's service tier level
  primaryURL:
    type: Url
    canIdentify: true
    label: Primary URL
    description: The main url the product is served on
  lifecycleStage:
    type: ProductLifecycle
    canFilter: true
    label: Lifecycle stage
    description: Lifecycle stage of the product



