#!/usr/bin/env bash

mkdir -p neo4j/{plugins,logs,data}
wget -O neo4j/plugins/apoc-4.1.0.4-all.jar https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.1.0.4/apoc-4.1.0.4-all.jar
chmod 0644 neo4j/plugins/*.jar
ls -la neo4j/plugins
