#!/usr/bin/env bash

mkdir -p neo4j/{plugins,logs,data}
wget -O neo4j/plugins/apoc-3.2.3.6-all.jar https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.2.3.6/apoc-3.2.3.6-all.jar
chmod 0644 neo4j/plugins/*.jar
ls -la neo4j/plugins
