#!/usr/bin/env bash

BOLT_PORT=7687

echo "Waiting up to 2 minutes for neo4j bolt port ($BOLT_PORT)"

for i in {1..120};
    do
        nc -z 127.0.0.1 $BOLT_PORT
        is_up=$?
        if [ $is_up -eq 0 ]; then
            echo
            echo "Successfully started, neo4j bolt available on $BOLT_PORT"
            break
        fi
        sleep 1
        echo -n "."
done
echo
